DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS PERMISSION;
DROP TABLE IF EXISTS PERSON_PERMISSION;

CREATE TABLE PERSON (
  ID INT NOT NULL ,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL ,
  STATUS VARCHAR(3) NOT NULL ,
  PASSWORD VARCHAR(255) NOT NULL ,
  PRIMARY KEY (ID) ,
  CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PERMISSION (
  ID INT NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PERSON_PERMISSION (
  ID_PERSON INT NOT NULL ,
  ID_PERMISSION INT NOT NULL ,
  PRIMARY KEY (ID_PERSON ,ID_PERMISSION),
  FOREIGN KEY (ID_PERSON) REFERENCES person(id),
  FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION(ID)

);

CREATE SEQUENCE PERSON_SEQ START 3;



INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (1 ,'ADM');
INSERT INTO PERMISSION (ID, DESCRIPTION) VALUES (2 ,'USER');

INSERT INTO PERSON (ID, NAME, EMAIL, STATUS, PASSWORD) VALUES (1,'ADM - plus', 'plusNoReply@gmail.com', 'A', '$2a$04$X3d3CgPOwzELOZyXwdL/2eRnApJ.rtNE6e3BJZLjr8SNlK5Fs6ire');
INSERT INTO PERSON (ID, NAME, EMAIL, STATUS, PASSWORD) VALUES (2,'Pedro Vitor Meira Ciria', 'pv.ciria@gmail.com', 'A', '$2a$04$X3d3CgPOwzELOZyXwdL/2eRnApJ.rtNE6e3BJZLjr8SNlK5Fs6ire');

INSERT INTO PERSON_PERMISSION (ID_PERSON, ID_PERMISSION) VALUES (1, 1);
INSERT INTO PERSON_PERMISSION (ID_PERSON, ID_PERMISSION) VALUES (2, 1);

