server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PvMeira/spring-cloud-configs
# Log configuration
logging:
    config: file:logback-spring.xml
endpoints:
      logview:
          path: log